openapi: 3.0.0
info:
  title: User and Event Management API
  version: 1.0.0
  description: API для управления пользователями и мероприятиями

servers:
  - url: http://localhost:8081

tags:
  - name: Users
    description: API для управления пользователями
  - name: Events
    description: API для управления мероприятиями

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: API_KEY

security:
  - ApiKeyAuth: []

paths:
  /users:
    post:
      summary: Создать нового пользователя
      tags: [ Users ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Имя пользователя
                  example: John Doe
                email:
                  type: string
                  description: Email пользователя
                  example: john.doe@example.com
      responses:
        '201':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID созданного пользователя
                  name:
                    type: string
                    description: Имя пользователя
                  email:
                    type: string
                    description: Email пользователя
        '400':
          description: Ошибка валидации или email уже существует
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Сообщение об ошибке
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Сообщение об ошибке

    get:
      summary: Получить список всех пользователей
      tags: [ Users ]
      responses:
        '200':
          description: Успешный ответ с массивом пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID пользователя
                    name:
                      type: string
                      description: Имя пользователя
                    email:
                      type: string
                      description: Email пользователя
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Сообщение об ошибке

  /events:
    get:
      summary: Получить список всех мероприятий
      tags: [ Events ]
      responses:
        '200':
          description: Успешный ответ с массивом мероприятий
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID мероприятия
                    title:
                      type: string
                      description: Заголовок мероприятия
                    description:
                      type: string
                      description: Описание мероприятия
                    date:
                      type: string
                      format: date-time
                      description: Дата мероприятия
                    createdBy:
                      type: integer
                      description: ID создателя мероприятия
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Сообщение об ошибке

    post:
      summary: Создать новое мероприятие
      tags: [ Events ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Заголовок мероприятия
                description:
                  type: string
                  description: Описание мероприятия
                date:
                  type: string
                  format: date-time
                  description: Дата мероприятия
                createdBy:
                  type: integer
                  description: ID создателя мероприятия
      responses:
        '201':
          description: Мероприятие успешно создано
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID созданного мероприятия
                  title:
                    type: string
                  description:
                    type: string
                  date:
                    type: string
                    format: date-time
                  createdBy:
                    type: integer
        '400':
          description: Ошибка валидации или пользователь не найден
        '500':
          description: Ошибка сервера

  /events/{id}:
    get:
      summary: Получить мероприятие по ID
      tags: [ Events ]
      parameters:
        - name: id
          in: path
          required: true
          description: ID мероприятия
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ с мероприятием
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  date:
                    type: string
                    format: date-time
                  createdBy:
                    type: integer
        '404':
          description: Мероприятие не найдено
        '500':
          description: Ошибка сервера

    put:
      summary: Обновить мероприятие по ID
      tags: [ Events ]
      parameters:
        - name: id
          in: path
          required: true
          description: ID мероприятия
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Заголовок мероприятия
                description:
                  type: string
                  description: Описание мероприятия
                date:
                  type: string
                  format: date-time
                  description: Дата мероприятия
                createdBy:
                  type: integer
                  description: ID создателя мероприятия
      responses:
        '200':
          description: Мероприятие успешно обновлено
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  date:
                    type: string
                    format: date-time
                  createdBy:
                    type: integer
        '400':
          description: Не переданы поля для обновления
        '404':
          description: Мероприятие не найдено
        '500':
          description: Ошибка сервера

    delete:
      summary: Удалить мероприятие по ID
      tags: [ Events ]
      parameters:
        - name: id
          in: path
          required: true
          description: ID мероприятия
          schema:
            type: integer
      responses:
        '204':
          description: Мероприятие успешно удалено
        '404':
          description: Мероприятие не найдено
        '500':
          description: Ошибка сервера

  /events/{id}/image:
    post:
      summary: Загрузить изображение для мероприятия
      tags: [ Events ]
      parameters:
        - name: id
          in: path
          required: true
          description: ID мероприятия
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: Изображение для загрузки
      responses:
        '200':
          description: Изображение успешно загружено и мероприятие обновлено
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  date:
                    type: string
                    format: date-time
                  createdBy:
                    type: integer
                  image_url:
                    type: string
                    description: URL загруженного изображения
        '400':
          description: Файл не загружен
        '404':
          description: Мероприятие не найдено
        '500':
          description: Ошибка сервера
